-- Khám phá (Level 1 - CTV)
INSERT INTO lessons (id, level, title, content, video_url, quiz_json, order_num) VALUES
('les-001', 'Khám phá', 'Chào mừng đến Hive Academy', 'Giới thiệu hệ thống và cách thức hoạt động của Hive Academy. Tìm hiểu về lộ trình học tập và các quyền lợi khi tham gia.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Hive Academy là gì?","options":["Hệ thống đào tạo","Game online","Mạng xã hội"],"answer":0}]', 1),
('les-002', 'Khám phá', '5AM Miracle - Bí quyết năng suất', 'Tại sao dậy sớm 5AM lại quan trọng với người làm sales. Cách thiết lập thói quen dậy sớm và duy trì nó.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Mấy giờ là 5AM Miracle?","options":["5:00 AM","6:00 AM","7:00 AM"],"answer":0}]', 2),
('les-003', 'Khám phá', 'Tư duy Sale đa cấp', 'Hiểu đúng về mô hình MLM và tư duy đúng của người làm sale. Phân biệt MLM hợp pháp và lừa đảo.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"MLM hợp pháp dựa trên?","options":["Bán sản phẩm","Tuyển người","Đầu tư"],"answer":0}]', 3),
('les-004', 'Khám phá', 'Kỹ năng Connect cơ bản', 'Cách bắt chuyện và kết nối với khách hàng mới. Các bước chuẩn bị trước khi gọi điện.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Bước đầu tiên khi connect?","options":["Tìm hiểu khách hàng","Gọi điện ngay","Nhắn tin spam"],"answer":0}]', 4),
('les-005', 'Khám phá', 'Sản phẩm và USP', 'Giới thiệu tổng quan về sản phẩm và Unique Selling Proposition. Cách nhớ các thông tin quan trọng.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"USP là viết tắt của?","options":["Unique Selling Proposition","User Service Platform","Universal Sales Plan"],"answer":0}]', 5);

-- Tân Binh (Level 2 - Đại lý)
INSERT INTO lessons (id, level, title, content, video_url, quiz_json, order_num) VALUES
('les-006', 'Tân Binh', 'Quy trình SP (Sale Process)', '5 bước chuẩn trong quy trình sale: Prospect → Connect → Present → Close → Follow-up. Chi tiết từng bước và cách thực hiện.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Bước 3 của SP là?","options":["Present","Connect","Close"],"answer":0}]', 6),
('les-007', 'Tân Binh', 'Kỹ thuật Close cơ bản', 'Các kỹ thuật chốt sale đơn giản: Direct Close, Assumptive Close, Alternative Close. Khi nào nên dùng từng kỹ thuật.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Kỹ thuật chốt trực tiếp là?","options":["Direct Close","Soft Close","Hard Close"],"answer":0}]', 7),
('les-008', 'Tân Binh', 'Xử lý từ chối (Objection Handling)', 'Các loại từ chối thường gặp: Giá cao, Để suy nghĩ, Không cần. Cách phản hồi từng loại từ chối.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Khi khách nói giá cao, nên?","options":["Chứng minh giá trị","Giảm giá ngay","Bỏ qua"],"answer":0}]', 8),
('les-009', 'Tân Binh', 'Zoom 1 bam - Kỹ năng presentations', 'Cách chuẩn bị và thực hiện buổi presentation 1-1 hiệu quả. Sử dụng zoom và các công cụ hỗ trợ.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Zoom 1 bam nghĩa là?","options":["1 khách duy nhất","1 giờ","1 lần gọi"],"answer":0}]', 9),
('les-010', 'Tân Binh', 'Review và Self-coaching', 'Cách tự đánh giá hiệu suất làm việc hàng ngày. Sử dụng checklist review 6 habits.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Review nên làm?","options":["Cuối mỗi ngày","Đầu tuần","Cuối tháng"],"answer":0}]', 10);

-- Chiến Binh (Level 3 - Coach 1S)
INSERT INTO lessons (id, level, title, content, video_url, quiz_json, order_num) VALUES
('les-011', 'Chiến Binh', 'Team Building cơ bản', 'Cách tuyển dụng và đào tạo CTV mới. Quy trình đãi và giữ chân người giỏi. Xây dựng văn hóa team.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Team building bắt đầu từ?","options":["Tuyển đúng người","Đào tạo sau","Chia hoa hồng"],"answer":0}]', 11),
('les-012', 'Chiến Binh', 'SP nâng cao - Upsell & Cross-sell', 'Kỹ thuật bán thêm và bán chéo. Nhận biết tín hiệu mua hàng và timing phù hợp.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Upsell là?","options":["Bán sản phẩm cao cấp hơn","Bán thêm sản phẩm khác","Bán cho khách cũ"],"answer":0}]', 12),
('les-013', 'Chiến Binh', 'DISC trong Sales', 'Ứng dụng DISC để hiểu khách hàng. Cách nhận diện 4 nhóm tính cách và cách tiếp cận phù hợp.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Loại tính cách chiếm 35%?","options":["S - Steady","D - Dominance","I - Influence"],"answer":2}]', 13),
('les-014', 'Chiến Binh', 'Quản lý thời gian cho Leader', 'Ma trận Eisenhower, Time blocking cho người làm MLM. Cân bằng giữa tuyển dụng và bán hàng.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Việc quan trọng chưa gấp là?","options":["Q2 - Không khẩn cấp","Q1 - Khẩn cấp","Q3 - Gián đoạn"],"answer":0}]', 14),
('les-015', 'Chiến Binh', 'Kỹ năng Trainer', 'Cách thiết kế bài giảng và đào tạo team. Sử dụng GROW model trong coaching.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"GROW model có mấy bước?","options":["4","3","5"],"answer":0}]', 15);

-- Chỉ Huy (Level 4 - Coach 2-3S)
INSERT INTO lessons (id, level, title, content, video_url, quiz_json, order_num) VALUES
('les-016', 'Chỉ Huy', 'Campaign và Event策划', 'Cách lập kế hoạch Campaign bán hàng. Tổ chức sự kiện offline/online cho team. KPIs và đo lường.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Campaign cần xác định đầu tiên?","options":["Mục tiêu (Goal)","Ngân sách","Đội ngũ"],"answer":0}]', 16),
('les-017', 'Chỉ Huy', 'Advanced Closing Techniques', 'Chốt sale giá trị lớn (High-ticket). Xử lý phòng tuyến nhiều lớp. Necktop closing.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"High-ticket closing cần?","options":["Lòng tin sâu","Giá rẻ","Khuyến mãi"],"answer":0}]', 17),
('les-018', 'Chỉ Huy', 'Data-driven Sales', 'Sử dụng dashboard và analytics để ra quyết định. Đọc hiểu các chỉ số quan trọng.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Chỉ số đo lường chuyển đổi?","options":["Conversion Rate","Page Views","Bounce Rate"],"answer":0}]', 18),
('les-019', 'Chỉ Huy', 'Conflict Resolution', 'Giải quyết xung đột trong team. Các mô hình mediation và negotiation.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Bước 1 giải quyết xung đột?","options":["Lắng nghe","Kết luận","Tách team"],"answer":0}]', 19),
('les-020', 'Chỉ Huy', 'Personal Branding cho Leader', 'Xây dựng thương hiệu cá nhân trên social media. Content strategy cho leader.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Personal branding cốt lõi là?","options":["Sự nhất quán","Likes nhiều","Follower đông"],"answer":0}]', 20);

-- Tướng Quân (Level 5 - Mentor)
INSERT INTO lessons (id, level, title, content, video_url, quiz_json, order_num) VALUES
('les-021', 'Tướng Quân', 'Xây dựng Hệ thống (System Building)', 'Từ leader đến hệ thống tự vận hành. Quy trình chuẩn hóa (SOP) cho toàn team.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"SOP viết tắt của?","options":["Standard Operating Procedure","System Of People","Sales Operation Plan"],"answer":0}]', 21),
('les-022', 'Tướng Quân', 'Chiến lược mở rộng thị trường', 'Cách nhân rộng mô hình sang vùng mới. Market research và entry strategy.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Bước quan trọng nhất mở rộng?","options":["Nghiên cứu thị trường","Thuê văn phòng","Tuyển nhiều người"],"answer":0}]', 22),
('les-023', 'Tướng Quân', 'Mentorship và Legacy', 'Đào tạo thế hệ lãnh đạo kế cận. Tạo ra văn hóa và di sản để lại.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Mentor khác coach ở?","options":["Dài hạn & tâm linh","Ngắn hạn & kỹ năng","Không khác nhau"],"answer":0}]', 23),
('les-024', 'Tướng Quân', 'Financial Management cho Team', 'Quản lý dòng tiền team, thuế, và đầu tư lợi nhuận. Báo cáo tài chính cơ bản.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Cash flow là?","options":["Dòng tiền","Lợi nhuận","Tài sản"],"answer":0}]', 24),
('les-025', 'Tướng Quân', 'Tổng kết - Hành trình Tướng Quân', 'Nhìn lại toàn bộ lộ trình từ CTV đến Tướng Quân. Bài học và tầm nhìn tương lai.', 'https://www.youtube.com/embed/dQw4w9WgXcQ', '[{"q":"Yếu tố quan trọng nhất thành công?","options":["Kiên trì","Thông minh","May mắn"],"answer":0}]', 25);
